### ISSUE TITLE
does this need a time

### ISSUE THREAD

**Issue by aric87** [gfed53/ultimate-youtube-searcher#7]
https://github.com/gfed53/ultimate-youtube-searcher/blob/master/src/partials/search/searchController.js#L32

**Comment by gfed53** [comment]
If I don't wrap that execution in a timeout, I get this error:

angular.js:13424TypeError: Cannot read property 'offsetWidth' of null

I guess it may be a Google Maps API issue, where certain values are trying to be retrieved before the map itself is created. I'm not really sure, but I found that using a timeout solves this problem.

**Comment by aric87** [comment]
using the timeout is ok, but it should have a duration right?

**Comment by gfed53** [comment]
http://stackoverflow.com/questions/20610450/angulajs-angularjs-timeout-without-delay-parameters-reason

I found out about this at some point, and I can see how it can work in this situation.
